# Generated by Django 6.0.1 on 2026-01-24 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
        migrations.AddField(
            model_name='dog',
            name='lister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_dogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.CharField(blank=True, help_text='City or area', max_length=100),
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dogs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dog.dog')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
