# Generated by Django 6.0.1 on 2026-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_dog_is_approved_dog_lister_dog_location_dogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='story',
        ),
        migrations.AddField(
            model_name='dog',
            name='behaviour',
            field=models.CharField(default='', help_text='e.g., Friendly, Energetic, Calm, Playful', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Adoption fee', max_digits=10),
        ),
    ]
