# Generated by Django 6.0.1 on 2026-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_remove_dog_story_dog_behaviour_dog_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_months',
            field=models.IntegerField(default=0, help_text='Age in months for sorting'),
        ),
    ]
