# Generated by Django 6.0.1 on 2026-01-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_dog_age_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age_months',
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(help_text='Age in months'),
        ),
    ]
