# Generated by Django 6.0.1 on 2026-01-16 14:21

from django.db import migrations
import random
import string


def generate_order_numbers(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.all():
        if not order.order_number:
            # Generate unique random order number
            while True:
                random_str = ''.join(random.choices(string.ascii_uppercase + string.digits, k=9))
                order_number = f"ORD-{random_str}"
                if not Order.objects.filter(order_number=order_number).exists():
                    order.order_number = order_number
                    order.save()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_order_number'),
    ]

    operations = [
        migrations.RunPython(generate_order_numbers),
    ]
