# Generated by Django 6.0.1 on 2026-01-16 17:06

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1
            while Product.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
